CREATE DATABASE GER_JOIN;

USE GER_JOIN;

CREATE TABLE funcionarios (
    COD INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    ESPECIALIDADE VARCHAR(255) NOT NULL
);

CREATE TABLE dependentes (
    COD INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    COD_FUNC INT,
    FOREIGN KEY (COD_FUNC) REFERENCES funcionarios(COD)
);

INSERT INTO funcionarios (NOME, ESPECIALIDADE)
VALUES ("JOSÉ", "ENGENHEIRO"),
       ("JOÃO", "MESTRE DE OBRAS"),
       ("MARIA", "CONTABILISTA");

INSERT INTO dependentes (NOME, COD_FUNC)
VALUES ("PEDRO", 1),
       ("PAULO", 1),
       ("LUANA", 3),
       ("FABIO", 3);

SELECT funcionarios.NOME, dependentes.NOME
FROM funcionarios
INNER JOIN dependentes ON funcionarios.COD = dependentes.COD_FUNC
WHERE funcionarios.COD = 1;

SELECT FUNC.NOME AS NOME_FUNC, DEP.NOME AS NOME_DEP
FROM funcionarios FUNC
LEFT JOIN dependentes DEP ON FUNC.COD = DEP.COD_FUNC;

SELECT FUNC.NOME AS NOME_FUNC, DEP.NOME AS NOME_DEP
FROM funcionarios FUNC
LEFT JOIN dependentes DEP ON FUNC.COD = DEP.COD_FUNC
WHERE DEP.NOME IS NULL;

SELECT FUNC.NOME AS NOME_FUNC, DEP.NOME AS NOME_DEP
FROM funcionarios FUNC
RIGHT JOIN dependentes DEP ON FUNC.COD = DEP.COD_FUNC;

SELECT FUNC.NOME AS NOME_FUNC, DEP.NOME AS NOME_DEP
FROM funcionarios FUNC
RIGHT JOIN dependentes DEP ON FUNC.COD = DEP.COD_FUNC
WHERE FUNC.COD IS NULL;

CREATE VIEW VW_LISTA_FUNCIONARIOS AS
SELECT NOME, ESPECIALIDADE
FROM funcionarios;

SELECT * FROM VW_LISTA_FUNCIONARIOS;

CREATE VIEW VW_LISTA_DEPENDENTES AS
SELECT NOME
FROM dependentes;

CREATE VIEW VW_FUNCIONARIOS_COM_DEPENDENTES AS
SELECT funcionarios.NOME AS FUNC_NOME, dependentes.NOME AS DEP_NOME
FROM funcionarios 
INNER JOIN dependentes ON funcionarios.COD = dependentes.COD_FUNC;

CREATE VIEW VW_FUNCIONARIOS_E_DEPENDENTES AS
SELECT funcionarios.NOME AS FUNC_NOME, dependentes.NOME AS DEP_NOME
FROM funcionarios 
LEFT JOIN dependentes ON funcionarios.COD = dependentes.COD_FUNC;

CREATE VIEW VW_DEPENDENTES AS
SELECT funcionarios.NOME AS FUNC_NOME, dependentes.NOME AS DEP_NOME
FROM funcionarios 
RIGHT JOIN dependentes ON funcionarios.COD = dependentes.COD_FUNC;

CREATE VIEW VW_DEPENDENTES_EXCLUINDO_FUNCIONARIOS AS
SELECT FUNC.NOME AS FUNC_NOME, DEP.NOME AS DEP_NOME
FROM funcionarios FUNC
RIGHT JOIN dependentes DEP ON FUNC.COD = DEP.COD_FUNC
WHERE FUNC.COD IS NULL;

CREATE VIEW VW_FUNCIONARIOS_EXCLUINDO_DEPENDENTES AS
SELECT FUNC.NOME AS FUNC_NOME, DEP.NOME AS DEP_NOME
FROM funcionarios FUNC
LEFT JOIN dependentes DEP ON FUNC.COD = DEP.COD_FUNC
WHERE DEP.COD IS NULL;
